### PR TITLE
Blender mesh exporter

### PR DESCRIPTION
**Pull request by Gorgious56**
First commit of blender exporter.

It is _relatively_ fast thanks to numpy.
Custom props on the objects are stored in the info dictionary, I used the `uuid` module for generating guid but maybe it can be managed elsewhere ?

Possible improvements :
- Support non-mesh objects (curves, text, gpencil, ...)
- Support Empty objects ? Is it allowed by dotbim ?
- Define objects with linked meshes as using the same mesh id (optimization)
- Create an addon for direct access in File > Import and File > Export
- What about modifiers ?
- Export all objects in the scene rather than all selected objects ?

Further question :
- dotbim seems to not support scale, is there a reason ? Simplicity ? It would be easier to write exporters/importers with a 4x4 matrix handler which takes care of loc, rot and scale at once.

### CODE REVIEW

**Comment by paireks** [comment]
I've tried it and it's awesome! 

- Regarding non-meshes: is there a way in Blender to convert other types of geometries into meshes and export them? Obviously not stuff like curve, which is not possible to convert, but e.g. some surfaces or spheres? I think it's the only thing missing (if there is such option in Blender to convert easily).
- Empty you mean element without a mesh? In .bim element = 1 mesh, so if that's what you mean then probably not ;)
- Yeah, there is always a place for that, not sure if it's easy to do for Blender ;)
- I'm not familiar with Blender addons, but sure, such direct access would be great
- Is there a way to get meshes "after" the modifiers? If I understand correctly, right now we get meshes, but without taking modifiers into an account, is it possible to take them though?
- I think both ways are ok :)
- Yes, scale is not supported. Thing is these 2 things (vector & rotation) are only for reusing of the same mesh multiple times (for optimization purposes) and actually this is what you normally have in AEC, e.g. you have 1 chair and place it in 100 different places with different rotation for each one. So scaling with such reuse of mesh happens really rarely. But you're right with the 4x4 matrix, I mean in many places it would be much easier just to get that matrix for it and use it. Issue was IMO people use these matrices as a black boxes and it's hard to figure out such matrices when you want to debug some boundary cases or test them. E.g. some construct 4x4 matrices that contain not only rotation, position and scaling but some other operation like shear. Also it was a bit easier for me to write importers once I know coordinates will be always in meters, not in any unit + scale in matrix. But it's obviously only opinions, both methods have their own drawbacks :)

**Comment by paireks** [comment]
Oh, I forgot, if it's OK for you I will add you as an author or you can move it to your repo, and I will link it to your repo there, what's best for you :) Also if you have some example file created, you can also place them somewhere.

**Comment by Gorgious56** [comment]
Okay thanks for the explanation, it makes sense. 
I'll try and add a few improvements to the script. 

To continue the discussion :
- Actually curves can be converted to meshes when it makes sense. They leverage [to_mesh](https://docs.blender.org/api/current/bpy.types.Object.html?highlight=to_mesh#bpy.types.Object.to_mesh) that's available to all object types in Blender. Nurbs surfaces can also be exported as meshes using the same method.
- So there is no notion of parenting, right ? Just trying to make the scope of the features very clear :)
- It's definitely possible to make objects that share the same data use the same mesh definition. You just have to be cautious about linked objects that have modifiers in blender, because the actual evaluated mesh can be very different from the original mesh. For instance the array modifier in blender doesn't create new objects, it duplicates the whole mesh inside of the mesh data-block.
- Yes it is possible to get the mesh after the modifiers are applied, in fact that's the current behaviour of the script with `obj.to_mesh`
- About scale I understand the choice, it is indeed more human readable and prevent weird shearing transforms. Let's roll with it then :)

And sure feel free to add me as author when it makes sense, absolutely no problem.

Stay tuned :)

**Comment by paireks** [comment]
Oh, that's great it has to_mesh method! Kind of weird that curve can be meshed, I'd have to see how it looks like then :D Regarding parenting: I'm not sure what parenting is, so I guess no, but maybe some sort of an example would help me to get it :) Should I add you with a nickname or there is your name somewhere I could find? Normally when something new is added I post it also on Linkedin, so if you have account there I will add you as well in a post (if you don't mind obviously) :)

**Comment by Gorgious56** [comment]
Oh you are right, simple curves are only exported as points since dotbim doesn't support standalone edges :) However you can export curves as meshes with a blender feature that lets you bevel it :

image

I guess parenting is called differently in other softwares, but it's basically associating different objects so that the transforms of the parent object propagates to the children objects. It can be used for instance to make coumpound objects behave as one object, but actually be formed by several entities.

Sure you can add my handle @Gorgious56 and / or my real name which is Nathan Hild. I'd be thrilled to be associated with your communication on linkedin ! My personal page : https://www.linkedin.com/in/nathan-hild/

I've just added a few commits which restructured a bit your original script, I hope it's okay ! But I've added functionality to import and export dotbim files directly from the interface. You just have to package the three .py files in a zip file called `dotbim.zip` and install it using the addon installer inside the user preferences and it'll add submenu items in the File > Export and File > Import menus :

image

You can import several files at a time too.

I'll just work a bit on optimizing linked meshes on export / import and add a sample file and I think it should be good to merge,

Cheers :)

**Comment by paireks** [comment]
Great, let me know when it's ready for tests, I will try it then :) please remember to update file info part for exporter, I don't know if it is anywhere in a Blender file where you can get some basic info about file, if not, then you can e.g. create time stamp there or something, and add to this dictionary :) Do I have to zip all these files to add them as Blender add-on or it's not necessary? I will update the Readme.md later for instructions ;)

**Comment by Gorgious56** [comment]
AFAIK Blender doesn't store anywhere the name of the author. I could write the name of the file though, or get the OS login with `os.getlogin` but I don't think it's a good idea since it's not related to the actual file and borderline privacy invasion. However a good compromise I think is to add a textbox in the exporter interface to setup the username.

I'll add the timestamp when the file is created, that shouldn't be too hard with `date.today`

To be able to install it as an addon you need to put all three files into a folder 

image

named `dotbim`

image

and create an archive from this folder. The name of the archive doesn't matter, usually it's a good place to add a version number to the package.

image

I've added an example addon zip with the current state of the PR to this message  :
[dotbim_1_0.zip](https://github.com/paireks/dotbim-blender/files/8159444/dotbim_1_0.zip)

Also, there is a way to download and install `dotbimpy` to the current blender installation folder with a script like this one https://drive.google.com/file/d/15sX4NhY65e25LUDl25GxqmGN9KAK-eWm/view?usp=sharing (it's for scipy but I use it for pretty much every 3rd party module I want installed in the Blender env), do you think it's worth adding to the addon or keep the current workflow of the user manually download it themselves ?

**Comment by paireks** [comment]
You're totally right with the file info. Sure, if we can make it easier to install needed package, then let's go that way. But do I get this correctly, that someone will still need to manually run such additional script before package installation (instead of current approach)?

**Comment by Gorgious56** [comment]
It can be done automatically with a few tweaks to the `__init__.py` file, I think there are 2 options :
- Check if the addon can be imported at startup, if not, download and install the package
- Add a button in the addon preferences that would automatically download and install the package when clicked. This has the advantage of not forcing anything on the user. Also the interface hangs for a bit when a package is downloaded with a script in Blender so it can be a bit frustrating when enabling an addon. Anyways maybe we should wait for someone to complain about current workflow before adding this feature :) Your call !

I added a sample file with a few duplicated suzannes, I think that's a hallmark of Blender so that should be a nice sample file to showcase :)

In any case the PR is ready for merging if you're okay with it. If not do tell me what changes you would like to see.

BTW here's how the exporter looks :

image

In the top right you can choose between exporting selected objects or all scene objects. And there is an input field for author name.

Cheers !

**Comment by paireks** [comment]
Ok @Gorgious56, I checked it out, it is amazing, I merged it already and updated readme (please check out if I got everything right there). I updated also main repo + website (dotbim.net) with Suzanne model displayed ;) I will post on Linkedin about it soon!

I think the only thing to hotfix is the Type, as right now Type for export is always a "Structure", but it probably should be the name taken from here:
image
So e.g. here elements would be Type = "IfcBeam". For import it works like this, but for export it probably should be like this.
Also in one model I got this during import: 
2022-03-01_16h18_10
I believe that for that specific model for some reason somewhere in dictionary there was long string probably, if Blender doesn't accept such long info, then either we leave it alone with such error or we cut it to 63 characters. Normally it shouldn't be that long though, it is some sort of an exception.

Thank you for all! It is great tool, really!

**Comment by Gorgious56** [comment]
Done and Done ! :)

Happy to help, don't hesitate to ping if / when you see something come up.

Cheers !

**Pull request merged**
